sudo: required

services:
  - docker

before_install:
  - docker build -f ./docker/dockerfiles/base/Dockerfile -t linagora/esn-base .
  - docker build -t chamerling/openpaas-esn .

script:
  - docker ps
